#!/usr/bin/env bash
# /init-deep — Generate hierarchical AGENTS.md files throughout the project
# Usage: bash ~/.qwen/scripts/init-deep.sh [project-root]
set -euo pipefail

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

PROJECT_ROOT="${1:-$(pwd)}"
GENERATED=0

info() { echo -e "  ${CYAN}→${NC} $1"; }
pass() { echo -e "  ${GREEN}✓${NC} $1"; GENERATED=$((GENERATED + 1)); }
warn() { echo -e "  ${YELLOW}⚠${NC} $1"; }

echo -e "${CYAN} oMoMoMoMo /init-deep${NC}"
echo ""

if [[ ! -d "$PROJECT_ROOT" ]]; then
  echo "Error: $PROJECT_ROOT is not a directory"
  exit 1
fi

# Generate root AGENTS.md if not exists
if [[ ! -f "$PROJECT_ROOT/AGENTS.md" ]]; then
  cat > "$PROJECT_ROOT/AGENTS.md" << 'ROOT_EOF'
# Project Context

## Overview
[Auto-generated by /init-deep. Edit this file with project-specific information.]

## Tech Stack
- [List primary languages, frameworks, and tools]

## Key Directories
- `src/` — Source code
- `tests/` — Test files
- `docs/` — Documentation

## Conventions
- Follow existing code style
- Write tests for new features
- Use conventional commits

## Running the Project
- Setup: [commands]
- Build: [commands]
- Test: [commands]
- Run: [commands]
ROOT_EOF
  pass "Created root AGENTS.md"
else
  warn "Root AGENTS.md already exists — skipping"
fi

# Scan for directories that should have their own AGENTS.md
find "$PROJECT_ROOT" -maxdepth 3 -type d \
  -not -path "*/node_modules/*" \
  -not -path "*/.git/*" \
  -not -path "*/dist/*" \
  -not -path "*/build/*" \
  -not -path "*/vendor/*" \
  -not -path "*/.qwen/*" \
  -not -path "*/.opencode/*" \
  -not -path "*/.sisyphus/*" \
  | while read -r dir; do

    # Skip if AGENTS.md already exists
    [[ -f "$dir/AGENTS.md" ]] && continue

    # Skip if directory is empty
    file_count=$(find "$dir" -maxdepth 1 -type f \( -name "*.ts" -o -name "*.js" -o -name "*.py" -o -name "*.go" -o -name "*.rs" -o -name "*.java" -o -name "*.md" -o -name "*.json" -o -name "*.yaml" -o -name "*.yml" -o -name "*.toml" -o -name "*.css" -o -name "*.html" \) 2>/dev/null | wc -l)
    [[ "$file_count" -eq 0 ]] && continue

    # Get relative path
    rel_path="${dir#$PROJECT_ROOT/}"
    [[ "$rel_path" == "$PROJECT_ROOT" ]] && continue

    # Generate AGENTS.md for this directory
    dir_name=$(basename "$dir")
    cat > "$dir/AGENTS.md" << DIR_EOF
# ${dir_name}/

## Purpose
[Describe what this directory contains and its role in the project.]

## Key Files
$(find "$dir" -maxdepth 1 -type f \( -name "*.ts" -o -name "*.js" -o -name "*.py" -o -name "*.go" -o -name "*.rs" -o -name "*.java" \) -exec basename {} \; 2>/dev/null | head -20 | while read -r f; do echo "- \`${f}\` — [description]"; done)

## Dependencies
- [What this module depends on]

## Dependents
- [What depends on this module]

## Notes
- [Any important context for agents working in this directory]
DIR_EOF
    pass "Created ${rel_path}/AGENTS.md"

  done

echo ""
echo "────────────────────────────────────────────────────────────"
echo -e "  ${GREEN}✓ $GENERATED AGENTS.md files generated${NC}"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Next: Edit each AGENTS.md with project-specific context."
echo "Agents will auto-read relevant files based on the working directory."
